author = "Matt Cowger"
canonifyurls = true
copyright = "&copy; 2018. All rights reserved."
paginate = 10
theme = "blackburn"
title = "blog.cowger.us"
[indexes]
tag = "tags"
topic = "topics"

[[menu.main]]
identifier = "about"
name = "About"
pre = "<i class='fa fa-user fa-fw'></i>"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "post"
name = "Posts"
pre = "<i class='fa fa-list fa-fw'></i>"
url = "/post/"
weight = 2
[[menu.main]]
pre = "<i class='fa fa-list fa-fw'></i>"
name = "Historical Content"
url = "https://github.com/mcowger/old_blog/tree/master/_posts"
weight = 3
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class='fa fa-home fa-fw'></i>"
url = "/"
weight = 1
[params]
brand = "matt cowger"
custom_css = ["css/my.css"]
custom_js = ["js/my.js"]
dateformat = "2006-01-02T00:00:00+00:00"
disqus = "blog-cowger-us"
googleanalytics = "UA-29218457-1"
highlightjs = "androidstudio"
highlightjs_extra_languages = ["yaml"]
subtitle = "rants on platforms, formula 1, containers, python, devops, and good technical choices"
[social]
github = "mcowger"
linkedin = "mcowger"
twitter = "mcowger"
youtube = "mcowger"
