---
pages:
- post/do-data-breaches-impact-shareholder-value---a-quick-analysis.md
- post/12-factors-in-the-real-world.md
- post/end-of-an-era.md
- post/a-new-stablemate.md
- post/goodbye-always-makes-my-throat-hurt.md
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
